on:
  push:
    branches:
      - "main"

#   schedule:
#     - cron: "0,15,30,45 * * * *"

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Echo date start
        run: date "+%H:%M:%S   %d/%m/%y"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release zip
        run: |
          sudo timedatectl set-timezone Europe/Berlin
          mkdir release
          cp "live/user.cfg" "release"
          mkdir -p "release/data/Localization/german_(germany)"
          cp "live/global.ini" "release/data/Localization/german_(germany)/"
          cd release
          echo "${{ vars.VERSION_FILE_TEXT }} $(date '+%d.%m.%y - %H:%M Uhr')" >> Versionstext.txt
          mv Versionstext.txt Version-$(date "+%d.%m.%y-%H.%M").txt
          zip -r "../${{ vars.ZIP_NAME_LIVE }}" *
      - name: Create Release New
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.run_number }}
          commit: main
          name: ${{ vars.RELEASE_TITLE_LIVE }}
          body: ${{ vars.RELEASE_BODY }}
          artifacts: ${{ vars.ZIP_NAME_LIVE }}

      - name: Echo date ende
        run: date "+%H:%M:%S   %d/%m/%y"
