on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

  schedule:
    - cron: "0,30 * * * *"

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Lies die [ReadMe](https://github.com/rjcncpt/StarCitizen-Deutsch-INI/blob/main/README.md) für mehr Informationen.
          draft: false
          prerelease: false
      - name: Echo Test
        run: echo ${{ vars.MAJOR }}